version: '3'

services:
  api:
    image: fibonacci_csharp
    build:
      context: ./src
      dockerfile: Dockerfile
    hostname: src
    restart: always
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "80:80"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "5"